name: picamera2 style checker
on:
  pull_request:
    branches: [ main ]

jobs:
  style-check:

    runs-on: [ self-hosted ]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        clean: true

    - name: Check style
      run: ${{github.workspace}}/tools/checkstyle.py $(git log --format=%P -1 | awk '{print $1 ".." $2}')
