name: picamera2 style checker
on:
  pull_request:
    branches: [ main ]

jobs:
  style-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        clean: true

    - name: Check style
      run: |
        pip3 install black
        black --check picamera2
